### ISSUE TITLE
Add logical grouping of elements on DFD

### ISSUE THREAD

**Issue by nozmore** [OWASP/pytm#10]
When drawing a DFD I will often group things logically on the diagram, different local file datastores might be together as are external services out of scope, various AWS services etc. Currently the diagram is draw with things in random places. Using a Boundary would accomplish this but in some cases there isn't a boundary.

I was thinking it may be useful to have a logical group similar to a Boundary using an inGroup property and when drawing the DFD the Group would not be visible.

**Comment by colesmj** [comment]
I have been thinking about Boundaries, and your group concept is useful for drawing purposes.

**Comment by izar** [comment]
Shouldn't be difficult to create a Group class derived from Boundary and make its default color white. I'll try it later.

**Comment by izar** [comment]
Can an element be both in a trust boundary and part of a group ? That will make things difficult regarding to layout.

**Comment by izar** [comment]
Would grouping be solved by painting all members of a group in a given unique color?

**Comment by colesmj** [comment]
To follow up on this, and @izar 's questions above - there are 2 types of groups: collections (groups of related items) and groups of like items, like @nozmore 's data store example above). I have been told recently that Boundaries is the way we are handling collections; would like to revisit that at some point. For grouping like objects, that can probably only happen within a Boundary for it to make sense. Color coding might be a good alternative when grouping can't be done i.e. all data stores are blue so they visually stand out on the diagram.

**Comment by izar** [comment]
I don't think Boundaries should be our way of treating collections - they have a strong inherent logical value that collections do not. We need a different mechanism. Coloring would be lost in printed form.

**Comment by izar** [comment]
dup of #113
