### ISSUE TITLE
README for report template not updated?

### ISSUE THREAD

**Issue by jeremyng123** [OWASP/pytm#101]
In the README, it says `{findings:repeat:* ...}`

but, the template given was:

```
|{findings:repeat:
<details>
  <summary>   {{item.id}}   --   {{item.description}}</summary>
  <h6> Targeted Element </h6>
  <p> {{item.target}} </p>
  <h6> Severity </h6>
  <p>{{item.severity}}</p>
  <h6>Example Instances</h6>
  <p>{{item.example}}</p>
  <h6>Mitigations</h6>
  <p>{{item.mitigations}}</p>
  <h6>References</h6>
  <p>{{item.references}}</p>
  &nbsp;
  &nbsp;
  &emsp;
</details>
}|
```

I am trying to change the template but no idea where i should look into to properly build a nested loop in md.

please assist!

**Comment by izar** [comment]
Whatever comes after the : is the body of the loop, so basically anything can go there. Myself I have never tried a nested loop. It will be interesting to see what you come up with!
