### ISSUE TITLE
DataSet change breaking report template

### ISSUE THREAD

**Issue by rgacote** [OWASP/pytm#124]
The recent DataSet issue (#77) breaks the report templates. 
The data column in the report now shows a class `__repr__`:

```
DataSet({<pytm.pytm.Data(User ID and SSL Cert.) at 0x105ef5ac0>})
```

Unless I'm misunderstanding something, I believe adding a `__str__` method to the DataSet class (on or about line 191) addresses this issue.

```
    def __str__(self):
        return ", ".join([d.name for d in self])
```

Looking forward to making good use of the new DataSet feature.

**Comment by nineinchnick** [comment]
We were missing a test for reports, thanks for reporting this!
