### ISSUE TITLE
Report with all elements and annotations

### ISSUE THREAD

**Issue by nozmore** [OWASP/pytm#15]
I know this is in all in the py file but it would be nice to have a readable report with all elements and annotations.

**Comment by nozmore** [comment]
This could also be added to the DFD diagram itself, add a subgraph at the bottom which contains text.

**Comment by izar** [comment]
i'm currently thinking along the lines of user writing a text file that would contain stuff like [[tm.description]], [[finding(separator)]] and that would take care of including the content. The second form is for tabular content, where you can say [[finding(|)]] if you're writing markdown or [[finding(whatever html uses as a cell separator in a table)]] if you're using html, that kind of thing.

**Comment by izar** [comment]
Added the templating capability.
