### ISSUE TITLE
{{item.target}} not rendering to report's threats section

### ISSUE THREAD

**Issue by cgarst** [OWASP/pytm#172]
I'm using the included example `tm.py` with `docs/template.md` and getting a blank `<p>  </p>` as every threat's "Targeted Element" where `{{item.target}}` is defined in the template. I assume the example threat model is supposed to match some of the conditions defined in `pytm/threatlib/threats.json` and show the matching element name (the specific process, dataflow, etc) within this field? Is this a bug or am I misunderstanding the functionality?

Running as documented: `python3 ./tm.py --report docs/template.md`

**Comment by izar** [comment]
Good catch, thanks! On it.
