### ISSUE TITLE
Threat Mitigations

### ISSUE THREAD

**Issue by nozmore** [OWASP/pytm#18]
Related to https://github.com/izar/pytm/issues/17

I saw Threat Mitigations in the TODO file and thought it might be useful to start a threat to brainstorm about it. 

The primary goal of implementing mitigation logic would be to:
1. Remove a threat (or mark it as remediated, not applicable)
2. Alter a threat's CVSS or Severity

Any other goals?

**Comment by izar** [comment]
I was thinking it could, in the style of threats.py, be a collection of pointers to mitigations that we could then add to the report.

**Comment by colesmj** [comment]
Would a mitigation be simply guidance, or would this be a detectable condition (and trigger an exclusion, as indicate in #14 ?

**Comment by izar** [comment]
I thought about starting simple with guidance, but I can see it moving
forward to be a condition. What do you guys think?

**Comment by izar** [comment]
Added by @avhadpooja
