### ISSUE TITLE
Errors when creating reports

### ISSUE THREAD

**Issue by sschaenz** [OWASP/pytm#188]
When generating a report with "basic_template.md" there is the error message:

```
AttributeError: 'TM' object has no attribute 'assumptions'
```

Expressions like: `{{item:call:getElementType}}` or `{{item:call:getFindingCount}}` from advanced_template.md will result in an error message, for example: `TypeError: unsupported format string passed to Actor.__format__`

A simple template I created works (without call:) and a Markdown file is generated.

I use Python 3.9.9 on MacOS. pytm 1.2.0 (installed with pip).

Greeting
Stefan

**Comment by izar-sqsp** [comment]
Thanks for the report!

Looks like something got out of sync on the package. I am releasing 1.2.1 that should fix that. Please test and let me know.

**Comment by izar** [comment]
1.2.1 released with a fix, please update and let us know if it is solved.

**Comment by sschaenz** [comment]
Just tested it successfully. All the problems I reported are solved. 

Thank you very much!
