### ISSUE TITLE
There be dragons here (cvss for weaknesses?)

### ISSUE THREAD

**Issue by colesmj** [OWASP/pytm#2]
https://github.com/izar/pytm/blob/24addb4370598c77bd5f8736e4c7c48ce18eceeb/pytm/pytm.py#L21

Consider using CWSS rather than CVSS for severity scoring, especially where threats != vulnerabilities.
Also consider adding a scoring interface so users can define their own scoring methods (with some pre-canned ones); perhaps this function would take a JSON file describing similarly to rules the conditions for each severity level?

**Comment by izar** [comment]
That's a great idea. But is CWSS mature enough? Haven't "people" standardized on CVSS by now, even though it is not the best solution?

**Comment by colesmj** [comment]
They have I suppose, but it is imprecise by itself, compounded with the imprecise-ness of a design time activity such as threat modeling.

**Comment by izar** [comment]
True. We agree that CWSS is better, but are we at a point where we want to push it forward?

**Comment by shambho** [comment]
Hi @colesmj ! How you doing? 

Regarding the scoring system, I'm inclined towards CVSS even though it's imperfect. I looked at the CWSS page and it has been a while since it was revised too (no revision since 2014). I think it'll be harder to sell yet another scoring system to developers.

**Comment by izar** [comment]
CVSS removed for the time being. Let's go there again once we figure out the right use cases.
