### ISSUE TITLE
Move DFD writer logic outside pytm

### ISSUE THREAD

**Issue by nozmore** [OWASP/pytm#20]
I'd like to move the writer logic outside pytm. Python isn't my first language so my terms might not be right but I'd like to create a interface for tmwriter so we can support other formats than graphviz.

One writer might just be a report for Threats, Mitigations, Elements and Annotations, another could be existing graphviz, another could be mxGraph (https://jgraph.github.io/mxgraph/javascript/examples/helloworld.html) or use mxGraph XML format which can be loaded into Draw.io (Extras->Edit Diagram)

`<mxGraphModel dx="1190" dy="727" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="850" pageHeight="1100" background="#ffffff" math="0" shadow="0">
  <root>
    <mxCell id="0"/>
    <mxCell id="1" parent="0"/>
    <mxCell id="2" value="Client" style="ellipse;whiteSpace=wrap;html=1;aspect=fixed;fontColor=#000000;align=center;" parent="1" vertex="1">
      <mxGeometry x="120" y="140" width="80" height="80" as="geometry"/>
    </mxCell>
    <mxCell id="3" value="Server" style="ellipse;whiteSpace=wrap;html=1;aspect=fixed;fontColor=#000000;align=center;" parent="1" vertex="1">
      <mxGeometry x="410" y="110" width="80" height="80" as="geometry"/>
    </mxCell>
    <mxCell id="4" value="" style="endArrow=classic;html=1;fontColor=#000000;exitX=1;exitY=0.5;entryX=0;entryY=0.5;" parent="1" source="2" target="3" edge="1">
      <mxGeometry width="50" height="50" relative="1" as="geometry"/>
    </mxCell>
  </root>
</mxGraphModel>
`

**Comment by izar** [comment]
If each element has a method to represent itself under any given format, it is trivial to add pre- and -post to TM.resolve() and have that format supported. I think that layering up would create unnecessary complication at this time - unless there's a pattern to doing it that I am missing.

**Comment by izar** [comment]
Let's keep what we have for now and get more convoluted down the road. mxGraph is the first add-on candidate.
