### ISSUE TITLE
SIDs prefix meaning

### ISSUE THREAD

**Issue by raulbarreras** [OWASP/pytm#202]
Hi!
I couldn't find the list of all possible prefixes and their meaning.
Some of them are easy: "INP" could mean "Input" or maybe "Input Validation", but it would be useful to have all the possible options and what they mean.
Thank you!

**Comment by izar** [comment]
To tell you the truth, there's no specific meaning or range. We needed unique id's and this looked like a good way of doing them at the time. There's no inherent meaning to them.

**Comment by raulbarreras** [comment]
Oh! Thank you!
