### ISSUE TITLE
Error with make image

### ISSUE THREAD

**Issue by tdeshapriya** [OWASP/pytm#203]
Hi All,

When I try to run `make image` I get bellow error. Any idea? Please help
```

docker build -t pytm .
unable to resolve docker endpoint: context "docker build -t pytm ." does not exist
make: *** [image] Error 1
```

**Comment by raphaelahrens** [comment]
What OS is used?

This looks to me like a problem with the local docker installation.

Have you tried running other docker commands, to make sure this is a problem of the Makefile and not the local installation?

**Comment by tdeshapriya** [comment]
I am using Mac OS.

`docker build -t pytm . `I ran this and it worked
