### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by izar** [OWASP/pytm#22]
It is getting big and probably will be bigger. We need to start looking at the setup framework so we are able to use the standard tooling and publish to package directory sites.

**Comment by colesmj** [comment]
I'll sign up to tackle this problem.

**Comment by izar** [comment]
I've added a first run on setup.py - used it to deploy to testpypi and install. 
There are problems with the import - it is only working with "from pytm.pytm import TM" so I clearly did something wrong in the file naming.

**Comment by izar** [comment]
Done. FIxed path too.
