### ISSUE TITLE
Outdated plantuml download link in Dockerfile

### ISSUE THREAD

**Issue by niklasbo** [OWASP/pytm#246]
Hi there,

the plantuml link in the Dockerfile is outdated.
https://github.com/izar/pytm/blob/b4ac2e05909d3076fd2e04c5e0af9f72857b7f90/Dockerfile#L15

When you open the link, you get a 302 / 301 http redirect. While Dockerfile build process I get an ssl trust issue.

Can I send you a PR? Otherwise can you update the link?

Kind Regards,
Niklas

**Comment by raphaelahrens** [comment]
Hi,

yes it is best to create a PR.
