### ISSUE TITLE
Suggestion: Move threats to their own module then import them

### ISSUE THREAD

**Issue by colesmj** [OWASP/pytm#3]
https://github.com/izar/pytm/blob/24addb4370598c77bd5f8736e4c7c48ce18eceeb/pytm/pytm.py#L224

Defined properly, this would allow selective import of threats, perhaps for more targeted analysis.

**Comment by izar** [comment]
Yep, take a look at the previous versions - I've tried playing with it but it got embroiled into double-dependencies: in order to have the class types in the threats we need to import them, and in order to have the threats accessible to TM, it needs to import them. It gets cyclic. Ideas?

**Comment by izar** [comment]
Going to try this: http://effbot.org/zone/import-confusion.htm

**Comment by izar** [comment]
Done!
