### ISSUE TITLE
How should I generate a report?

### ISSUE THREAD

**Issue by omerlh** [OWASP/pytm#36]
By looking on the doc I need to run:
```
tm.py --report REPORT (output report using the named template file)
```
What is this template file? Where can I find it?

**Comment by shambho** [comment]
@omerlh you may use the following template file to generate the report.

https://github.com/izar/pytm/blob/master/docs/template_test.md

**Comment by omerlh** [comment]
Aha I see. So I can create a similar JSON template or whatever I guess. Interesting. Should I open a PR to add it to the readme?
It worked BTW, look like there is a small bug:
```
Lambda does not handle resource consumption on element "cleanDBevery6hours
```
Missing closing " :)

**Comment by shambho** [comment]
PRs are most welcome! :) 

Please raise a PR if you have already addressed it or otherwise I'll update the Readme and fix the bug later this week. Thanks!
