### ISSUE TITLE
Alternative import mechanism

### ISSUE THREAD

**Issue by davevs** [OWASP/pytm#39]
As suggested in the comments on https://github.com/izar/pytm/pull/38 a proper way to import threat lists would be desirable. The goal would be to have an easy way to import threat lists based on existing lists of controls. (Many companies already have something like that in excel or csv, so it would be a matter of tweaking in the right layout and of you go).

Off course, it would also mitigate the dangerous use of eval() in my commit ;)

However the current dictionary structure makes this challenging. I first tried to output the existing dictionary and analyze what would be suitable to adopt, but so far my experiments aren't really successful:

csv.writer
seems to do the job, but gives full class names and throws all values in a big string. I will do some more research.

json.dump and json.dumps
crash on output with complaints about structure

pickle.dump
works, but creates unreadable file; not suitable as import mechanism

jsonpickle
works, but adds more meta info 

Not sure what the best solution would be, so I'm  open to suggestions.

**Comment by davevs** [comment]
Got the import working with pandas, but source and target are now placed in the dictionary as strings, which breaks the logic in the pytm module :(

**Comment by davevs** [comment]
Got the import from (multiple) csv running now using pandas. Also did the normalisation with pandas. Threat dictionary looks good at first sight, but will do some thorough testing before submitting. 
I can also make the csv parser a separate tool dumping to json and convert threat.py to import json files.

**Comment by izar** [comment]
We are adding unit tests soon and once it is done, we'll work on integrating your PR. Thanks!
