### ISSUE TITLE
Boundaries with same name are grouping together

### ISSUE THREAD

**Issue by mikicho** [OWASP/pytm#45]
I'm not sure if it's by intent or not, but if I have two boundaries with the same name the components rendered into one boundary.
i.e:
```
dbVpc = Boundary("VPC")
serviceVpc = Boundary("VPC")

...

db = Datastore("Postgres Aurora")
db.inBoundary = dbVpc
server = Server("Server")
server.inBoundary = serviceVpc
```
Generates the following:

![image](https://user-images.githubusercontent.com/11459632/65386215-25e6b480-dd41-11e9-8cc2-9c1b971ca36c.png)

**Comment by lfservin** [comment]
That might be more of a graphviz problem. Have you looked at the dfd output? does the dot command complain about something?

**Comment by redshiftzero** [comment]
hmm I just ran into this too, it looks like what is happening is that the truncated hashes used as the node ID for graphviz (e.g. `fedfcbcecdeaaeefcdaefdb`) are derived only from the name (see the [`_uniq_name()` function](https://github.com/izar/pytm/blob/master/pytm/pytm.py#L121)). As such, if the names are equal, the hashes will collide, and graphviz will then only render a single instance of the node. 

Here's a self-contained reproducer:

```
#!/usr/bin/env python3
from pytm.pytm import Actor, Boundary, TM, Server

tm = TM("test")
tm.description = "test"

server_rack = Boundary("bar")

app_server = Server("foo")
app_server.inBoundary = server_rack

mon_server = Server("foo")
mon_server.inBoundary = server_rack

admin = Actor("beep")
admin.inBoundary = server_rack

tm.process()
```

Even though there are two `Server` objects called `foo`, only one renders:

![dfd](https://user-images.githubusercontent.com/7832803/68448434-7ad77080-01b1-11ea-934c-e9b8d0d919e6.png)
