### ISSUE TITLE
Multiple boundaries for one component

### ISSUE THREAD

**Issue by mikicho** [OWASP/pytm#46]
I want to render two boundaries around one component (for example if I have a database which protected by user/password and reside in VPC).

**Comment by lfservin** [comment]
wouldn't this still be a DB? you could then say in its attributes, in the "authenticationScheme" that password is used. 
The DB would be within a VPC. This VPC is the boundary within which the DB resides.

**Comment by mikicho** [comment]
I'm not a security pro, but the user/password credentials aren't a boundary?

**Comment by lfservin** [comment]
They aren't a boundary per se. They are you methods to identify(username) and authenticate(password) an entity (aka as a principal) trying to "talk" to a system. 

I would create the VPC as a boundary. I would then create the DB as a DataStore and make it belong to the VPC. I would then set the Datastore these attributes as:
        authenticatesSource: true
        authenticationScheme: basic
        authorizesSource: true (only if you have more than one type of user accessing the DB from the other system, which of course you have).

**Comment by mikicho** [comment]
Ok, Thanks!
