### ISSUE TITLE
AttributeError: 'Datastore' object has no attribute 'authenticatesDestination'

### ISSUE THREAD

**Issue by rgacote** [OWASP/pytm#48]
A clean install from pip Returns this error when generating a report. 
The problem is on line 338:
`     _authenticatesDestination = varBool(False)`
which has a leading `_` character.

The code is correct in master branch in version control. 

Is it possible to get an updated pip installer released?

**Comment by lfservin** [comment]
you can get rid of the problem by declaring this mandatory attribute.  My understanding is that attributes that begin with underscore (_) are mandatory.

**Comment by rgacote** [comment]
The error message says the code is looking for 'authenticatesDestination' without the leading underscore. Also, the current source code in GitHub does not have a leading underscore on that attribute.

**Comment by nineinchnick** [comment]
@izar looks like this has been already fixed, both in master and in latest version published on pypi and can be closed.
