### ISSUE TITLE
Can not make sequence diagrams

### ISSUE THREAD

**Issue by lareck** [OWASP/pytm#59]
It appears that there is an issue with making sequence diagrams with the latest release.

./tm.py --seq 
@startuml
actor cbdcbcbdaaddaadbdfadadfaaae as "User"
Traceback (most recent call last):
  File "./tm.py", line 64, in <module>
    tm.process()
  File "/opt/pytm/pytm/pytm.py", line 255, in process
    self.seq()
  File "/opt/pytm/pytm/pytm.py", line 234, in seq
    print("entity {0} as \"{1}\"".format(_uniq_name(e.name), e.name))
TypeError: _uniq_name() missing 1 required positional argument: 'obj_uuid'

**Comment by thneumann** [comment]
Hi Lance,
thanks for your posting. It is actually the same problem as I had in Issue #58 . However, you had a by far better error message. With your Input I was able to fix the problem. I created a pull request. After the pull request is approved you can try it yourself. I really appreciate your feedback.
Best regards
Thorben

**Comment by nineinchnick** [comment]
@izar looks like this has been fixed in #60 and can be closed.
