### ISSUE TITLE
Proposal: Create a new Data Element to generate threats based on privacy/compliance

### ISSUE THREAD

**Issue by avhadpooja** [OWASP/pytm#77]
Have a Table/Data element that has an attribute describing the type of data stored in it. Threat conditions could be based on the relationship of the data stored. e.g. If the table has two columns, username, and userSSN, it would lead to a privacy issue.

**Comment by izar** [comment]
i'm picking this one up.

**Comment by nineinchnick** [comment]
Done in #104
